### ISSUE TITLE
Progress Tracker

### ISSUE THREAD

**Issue by EmilyCook321** [EmilyCook321/mascota#28]
- [ ] New words learnt (basic overview)

- [ ] New words learnt list

- [ ] Set your new word goal for next week

- [ ] Continue playing button
